/*
** This program has been automatically generated by the
** second-level foreign language interface of the
** XSB System
*/

#include <stdio.h>
#include <string.h>
#include "/home/ken/XSB/emu/cinterf.h"
#include "/home/ken/XSB/emu/context.h"

/* New Definition: test(retval:output) from int btest(). */
prolog_int btest();
DllExport prolog_int call_conv test(CTXTdecl)
{
   prolog_term retvalOut;
   prolog_int retval;
   retvalOut = extern_reg_term(1);
   if(!is_var(retvalOut)) return FALSE;
   xsb_query_save(CTXTc 1);
   retval =   btest();
   if (xsb_query_restore(CTXT)) {  // restore regs to prepare for exit
      printf("Error finishing up btest.\n");
      fflush(stdout);
      return FALSE;
   }
   extern_c2p_int(retval,retvalOut);
   return TRUE;
}

/* New Definition: bt_create(dbname:input,predname:input,arity:input,indexon:input,retval:output) from int c_bt_create(string dbname,string predname,int arity,int indexon). */
prolog_int c_bt_create(char * dbname, char * predname, prolog_int arity, prolog_int indexon);
DllExport prolog_int call_conv bt_create(CTXTdecl)
{
   prolog_term dbnameIn;
   char *dbname;
   prolog_term prednameIn;
   char *predname;
   prolog_term arityIn;
   prolog_int  arity;
   prolog_term indexonIn;
   prolog_int  indexon;
   prolog_term retvalOut;
   prolog_int retval;
   dbnameIn = extern_reg_term(1);
   if (!is_string(dbnameIn)) return FALSE;
   dbname = extern_p2c_string(dbnameIn);
   prednameIn = extern_reg_term(2);
   if (!is_string(prednameIn)) return FALSE;
   predname = extern_p2c_string(prednameIn);
   arityIn = extern_reg_term(3);
   if (!is_int(arityIn)) return FALSE;
   arity = extern_p2c_int(arityIn);
   indexonIn = extern_reg_term(4);
   if (!is_int(indexonIn)) return FALSE;
   indexon = extern_p2c_int(indexonIn);
   retvalOut = extern_reg_term(5);
   if(!is_var(retvalOut)) return FALSE;
   xsb_query_save(CTXTc 5);
   retval =   c_bt_create(dbname, predname, arity, indexon);
   if (xsb_query_restore(CTXT)) {  // restore regs to prepare for exit
      printf("Error finishing up c_bt_create.\n");
      fflush(stdout);
      return FALSE;
   }
   extern_c2p_int(retval,retvalOut);
   return TRUE;
}

